/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.opentsx.data.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Represents a single time series episode containing a sequence of observations. License: Apache 2.0 */
@org.apache.avro.specific.AvroGenerated
public class Episode extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6804685436597725488L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Episode\",\"namespace\":\"org.opentsx.data.model\",\"doc\":\"Represents a single time series episode containing a sequence of observations. License: Apache 2.0\",\"fields\":[{\"name\":\"observationArray\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Observation\",\"doc\":\"A single data point in the time series.\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Unix timestamp in milliseconds.\"},{\"name\":\"uri\",\"type\":\"string\",\"doc\":\"The URI for additional information about unit of measurement.\"},{\"name\":\"value\",\"type\":\"double\",\"doc\":\"The measured value.\"}]}},\"doc\":\"List of observations in this episode.\"},{\"name\":\"label\",\"type\":[\"null\",\"string\"],\"doc\":\"Optional label for the episode.\",\"default\":null},{\"name\":\"tStart\",\"type\":[\"null\",\"long\"],\"doc\":\"Start time of the episode (epoch ms).\",\"default\":null},{\"name\":\"tEnd\",\"type\":[\"null\",\"long\"],\"doc\":\"End time of the episode (epoch ms).\",\"default\":null},{\"name\":\"zObservations\",\"type\":[\"null\",\"long\"],\"doc\":\"Number of observations.\",\"default\":null},{\"name\":\"increment\",\"type\":[\"null\",\"int\"],\"doc\":\"Time increment in ms between observations.\",\"default\":null},{\"name\":\"uri\",\"type\":[\"null\",\"string\"],\"doc\":\"Unique identifier URI for the episode.\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Episode> ENCODER =
      new BinaryMessageEncoder<Episode>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Episode> DECODER =
      new BinaryMessageDecoder<Episode>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Episode> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Episode> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Episode>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Episode to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Episode from a ByteBuffer. */
  public static Episode fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** List of observations in this episode. */
   private java.util.List<org.opentsx.data.model.Observation> observationArray;
  /** Optional label for the episode. */
   private java.lang.CharSequence label;
  /** Start time of the episode (epoch ms). */
   private java.lang.Long tStart;
  /** End time of the episode (epoch ms). */
   private java.lang.Long tEnd;
  /** Number of observations. */
   private java.lang.Long zObservations;
  /** Time increment in ms between observations. */
   private java.lang.Integer increment;
  /** Unique identifier URI for the episode. */
   private java.lang.CharSequence uri;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Episode() {}

  /**
   * All-args constructor.
   * @param observationArray List of observations in this episode.
   * @param label Optional label for the episode.
   * @param tStart Start time of the episode (epoch ms).
   * @param tEnd End time of the episode (epoch ms).
   * @param zObservations Number of observations.
   * @param increment Time increment in ms between observations.
   * @param uri Unique identifier URI for the episode.
   */
  public Episode(java.util.List<org.opentsx.data.model.Observation> observationArray, java.lang.CharSequence label, java.lang.Long tStart, java.lang.Long tEnd, java.lang.Long zObservations, java.lang.Integer increment, java.lang.CharSequence uri) {
    this.observationArray = observationArray;
    this.label = label;
    this.tStart = tStart;
    this.tEnd = tEnd;
    this.zObservations = zObservations;
    this.increment = increment;
    this.uri = uri;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return observationArray;
    case 1: return label;
    case 2: return tStart;
    case 3: return tEnd;
    case 4: return zObservations;
    case 5: return increment;
    case 6: return uri;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: observationArray = (java.util.List<org.opentsx.data.model.Observation>)value$; break;
    case 1: label = (java.lang.CharSequence)value$; break;
    case 2: tStart = (java.lang.Long)value$; break;
    case 3: tEnd = (java.lang.Long)value$; break;
    case 4: zObservations = (java.lang.Long)value$; break;
    case 5: increment = (java.lang.Integer)value$; break;
    case 6: uri = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'observationArray' field.
   * @return List of observations in this episode.
   */
  public java.util.List<org.opentsx.data.model.Observation> getObservationArray() {
    return observationArray;
  }

  /**
   * Sets the value of the 'observationArray' field.
   * List of observations in this episode.
   * @param value the value to set.
   */
  public void setObservationArray(java.util.List<org.opentsx.data.model.Observation> value) {
    this.observationArray = value;
  }

  /**
   * Gets the value of the 'label' field.
   * @return Optional label for the episode.
   */
  public java.lang.CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * Optional label for the episode.
   * @param value the value to set.
   */
  public void setLabel(java.lang.CharSequence value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'tStart' field.
   * @return Start time of the episode (epoch ms).
   */
  public java.lang.Long getTStart() {
    return tStart;
  }

  /**
   * Sets the value of the 'tStart' field.
   * Start time of the episode (epoch ms).
   * @param value the value to set.
   */
  public void setTStart(java.lang.Long value) {
    this.tStart = value;
  }

  /**
   * Gets the value of the 'tEnd' field.
   * @return End time of the episode (epoch ms).
   */
  public java.lang.Long getTEnd() {
    return tEnd;
  }

  /**
   * Sets the value of the 'tEnd' field.
   * End time of the episode (epoch ms).
   * @param value the value to set.
   */
  public void setTEnd(java.lang.Long value) {
    this.tEnd = value;
  }

  /**
   * Gets the value of the 'zObservations' field.
   * @return Number of observations.
   */
  public java.lang.Long getZObservations() {
    return zObservations;
  }

  /**
   * Sets the value of the 'zObservations' field.
   * Number of observations.
   * @param value the value to set.
   */
  public void setZObservations(java.lang.Long value) {
    this.zObservations = value;
  }

  /**
   * Gets the value of the 'increment' field.
   * @return Time increment in ms between observations.
   */
  public java.lang.Integer getIncrement() {
    return increment;
  }

  /**
   * Sets the value of the 'increment' field.
   * Time increment in ms between observations.
   * @param value the value to set.
   */
  public void setIncrement(java.lang.Integer value) {
    this.increment = value;
  }

  /**
   * Gets the value of the 'uri' field.
   * @return Unique identifier URI for the episode.
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * Unique identifier URI for the episode.
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /**
   * Creates a new Episode RecordBuilder.
   * @return A new Episode RecordBuilder
   */
  public static org.opentsx.data.model.Episode.Builder newBuilder() {
    return new org.opentsx.data.model.Episode.Builder();
  }

  /**
   * Creates a new Episode RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Episode RecordBuilder
   */
  public static org.opentsx.data.model.Episode.Builder newBuilder(org.opentsx.data.model.Episode.Builder other) {
    return new org.opentsx.data.model.Episode.Builder(other);
  }

  /**
   * Creates a new Episode RecordBuilder by copying an existing Episode instance.
   * @param other The existing instance to copy.
   * @return A new Episode RecordBuilder
   */
  public static org.opentsx.data.model.Episode.Builder newBuilder(org.opentsx.data.model.Episode other) {
    return new org.opentsx.data.model.Episode.Builder(other);
  }

  /**
   * RecordBuilder for Episode instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Episode>
    implements org.apache.avro.data.RecordBuilder<Episode> {

    /** List of observations in this episode. */
    private java.util.List<org.opentsx.data.model.Observation> observationArray;
    /** Optional label for the episode. */
    private java.lang.CharSequence label;
    /** Start time of the episode (epoch ms). */
    private java.lang.Long tStart;
    /** End time of the episode (epoch ms). */
    private java.lang.Long tEnd;
    /** Number of observations. */
    private java.lang.Long zObservations;
    /** Time increment in ms between observations. */
    private java.lang.Integer increment;
    /** Unique identifier URI for the episode. */
    private java.lang.CharSequence uri;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.opentsx.data.model.Episode.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.observationArray)) {
        this.observationArray = data().deepCopy(fields()[0].schema(), other.observationArray);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tStart)) {
        this.tStart = data().deepCopy(fields()[2].schema(), other.tStart);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.tEnd)) {
        this.tEnd = data().deepCopy(fields()[3].schema(), other.tEnd);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.zObservations)) {
        this.zObservations = data().deepCopy(fields()[4].schema(), other.zObservations);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.increment)) {
        this.increment = data().deepCopy(fields()[5].schema(), other.increment);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.uri)) {
        this.uri = data().deepCopy(fields()[6].schema(), other.uri);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Episode instance
     * @param other The existing instance to copy.
     */
    private Builder(org.opentsx.data.model.Episode other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.observationArray)) {
        this.observationArray = data().deepCopy(fields()[0].schema(), other.observationArray);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tStart)) {
        this.tStart = data().deepCopy(fields()[2].schema(), other.tStart);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.tEnd)) {
        this.tEnd = data().deepCopy(fields()[3].schema(), other.tEnd);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.zObservations)) {
        this.zObservations = data().deepCopy(fields()[4].schema(), other.zObservations);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.increment)) {
        this.increment = data().deepCopy(fields()[5].schema(), other.increment);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.uri)) {
        this.uri = data().deepCopy(fields()[6].schema(), other.uri);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'observationArray' field.
      * List of observations in this episode.
      * @return The value.
      */
    public java.util.List<org.opentsx.data.model.Observation> getObservationArray() {
      return observationArray;
    }

    /**
      * Sets the value of the 'observationArray' field.
      * List of observations in this episode.
      * @param value The value of 'observationArray'.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder setObservationArray(java.util.List<org.opentsx.data.model.Observation> value) {
      validate(fields()[0], value);
      this.observationArray = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'observationArray' field has been set.
      * List of observations in this episode.
      * @return True if the 'observationArray' field has been set, false otherwise.
      */
    public boolean hasObservationArray() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'observationArray' field.
      * List of observations in this episode.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder clearObservationArray() {
      observationArray = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'label' field.
      * Optional label for the episode.
      * @return The value.
      */
    public java.lang.CharSequence getLabel() {
      return label;
    }

    /**
      * Sets the value of the 'label' field.
      * Optional label for the episode.
      * @param value The value of 'label'.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder setLabel(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.label = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'label' field has been set.
      * Optional label for the episode.
      * @return True if the 'label' field has been set, false otherwise.
      */
    public boolean hasLabel() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'label' field.
      * Optional label for the episode.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder clearLabel() {
      label = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tStart' field.
      * Start time of the episode (epoch ms).
      * @return The value.
      */
    public java.lang.Long getTStart() {
      return tStart;
    }

    /**
      * Sets the value of the 'tStart' field.
      * Start time of the episode (epoch ms).
      * @param value The value of 'tStart'.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder setTStart(java.lang.Long value) {
      validate(fields()[2], value);
      this.tStart = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tStart' field has been set.
      * Start time of the episode (epoch ms).
      * @return True if the 'tStart' field has been set, false otherwise.
      */
    public boolean hasTStart() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tStart' field.
      * Start time of the episode (epoch ms).
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder clearTStart() {
      tStart = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'tEnd' field.
      * End time of the episode (epoch ms).
      * @return The value.
      */
    public java.lang.Long getTEnd() {
      return tEnd;
    }

    /**
      * Sets the value of the 'tEnd' field.
      * End time of the episode (epoch ms).
      * @param value The value of 'tEnd'.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder setTEnd(java.lang.Long value) {
      validate(fields()[3], value);
      this.tEnd = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'tEnd' field has been set.
      * End time of the episode (epoch ms).
      * @return True if the 'tEnd' field has been set, false otherwise.
      */
    public boolean hasTEnd() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'tEnd' field.
      * End time of the episode (epoch ms).
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder clearTEnd() {
      tEnd = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'zObservations' field.
      * Number of observations.
      * @return The value.
      */
    public java.lang.Long getZObservations() {
      return zObservations;
    }

    /**
      * Sets the value of the 'zObservations' field.
      * Number of observations.
      * @param value The value of 'zObservations'.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder setZObservations(java.lang.Long value) {
      validate(fields()[4], value);
      this.zObservations = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'zObservations' field has been set.
      * Number of observations.
      * @return True if the 'zObservations' field has been set, false otherwise.
      */
    public boolean hasZObservations() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'zObservations' field.
      * Number of observations.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder clearZObservations() {
      zObservations = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'increment' field.
      * Time increment in ms between observations.
      * @return The value.
      */
    public java.lang.Integer getIncrement() {
      return increment;
    }

    /**
      * Sets the value of the 'increment' field.
      * Time increment in ms between observations.
      * @param value The value of 'increment'.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder setIncrement(java.lang.Integer value) {
      validate(fields()[5], value);
      this.increment = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'increment' field has been set.
      * Time increment in ms between observations.
      * @return True if the 'increment' field has been set, false otherwise.
      */
    public boolean hasIncrement() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'increment' field.
      * Time increment in ms between observations.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder clearIncrement() {
      increment = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'uri' field.
      * Unique identifier URI for the episode.
      * @return The value.
      */
    public java.lang.CharSequence getUri() {
      return uri;
    }

    /**
      * Sets the value of the 'uri' field.
      * Unique identifier URI for the episode.
      * @param value The value of 'uri'.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.uri = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'uri' field has been set.
      * Unique identifier URI for the episode.
      * @return True if the 'uri' field has been set, false otherwise.
      */
    public boolean hasUri() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'uri' field.
      * Unique identifier URI for the episode.
      * @return This builder.
      */
    public org.opentsx.data.model.Episode.Builder clearUri() {
      uri = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Episode build() {
      try {
        Episode record = new Episode();
        record.observationArray = fieldSetFlags()[0] ? this.observationArray : (java.util.List<org.opentsx.data.model.Observation>) defaultValue(fields()[0]);
        record.label = fieldSetFlags()[1] ? this.label : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.tStart = fieldSetFlags()[2] ? this.tStart : (java.lang.Long) defaultValue(fields()[2]);
        record.tEnd = fieldSetFlags()[3] ? this.tEnd : (java.lang.Long) defaultValue(fields()[3]);
        record.zObservations = fieldSetFlags()[4] ? this.zObservations : (java.lang.Long) defaultValue(fields()[4]);
        record.increment = fieldSetFlags()[5] ? this.increment : (java.lang.Integer) defaultValue(fields()[5]);
        record.uri = fieldSetFlags()[6] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Episode>
    WRITER$ = (org.apache.avro.io.DatumWriter<Episode>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Episode>
    READER$ = (org.apache.avro.io.DatumReader<Episode>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
