/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.opentsx.data.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EpisodesNEW extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4519358967362672344L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EpisodesNEW\",\"namespace\":\"org.opentsx.data.model\",\"fields\":[{\"name\":\"observationValues\",\"type\":{\"type\":\"array\",\"items\":\"double\"},\"default\":[]},{\"name\":\"label\",\"type\":\"string\",\"default\":\"???\"},{\"name\":\"tStart\",\"type\":\"long\",\"default\":0},{\"name\":\"tEnd\",\"type\":\"long\",\"default\":1000},{\"name\":\"zObservations\",\"type\":\"long\",\"default\":1},{\"name\":\"increment\",\"type\":\"int\",\"doc\":\"Time increment in ms.\",\"default\":1000},{\"name\":\"uri\",\"type\":\"string\",\"default\":\"-\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EpisodesNEW> ENCODER =
      new BinaryMessageEncoder<EpisodesNEW>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EpisodesNEW> DECODER =
      new BinaryMessageDecoder<EpisodesNEW>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EpisodesNEW> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EpisodesNEW> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EpisodesNEW>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EpisodesNEW to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EpisodesNEW from a ByteBuffer. */
  public static EpisodesNEW fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<java.lang.Double> observationValues;
   private java.lang.CharSequence label;
   private long tStart;
   private long tEnd;
   private long zObservations;
  /** Time increment in ms. */
   private int increment;
   private java.lang.CharSequence uri;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EpisodesNEW() {}

  /**
   * All-args constructor.
   * @param observationValues The new value for observationValues
   * @param label The new value for label
   * @param tStart The new value for tStart
   * @param tEnd The new value for tEnd
   * @param zObservations The new value for zObservations
   * @param increment Time increment in ms.
   * @param uri The new value for uri
   */
  public EpisodesNEW(java.util.List<java.lang.Double> observationValues, java.lang.CharSequence label, java.lang.Long tStart, java.lang.Long tEnd, java.lang.Long zObservations, java.lang.Integer increment, java.lang.CharSequence uri) {
    this.observationValues = observationValues;
    this.label = label;
    this.tStart = tStart;
    this.tEnd = tEnd;
    this.zObservations = zObservations;
    this.increment = increment;
    this.uri = uri;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return observationValues;
    case 1: return label;
    case 2: return tStart;
    case 3: return tEnd;
    case 4: return zObservations;
    case 5: return increment;
    case 6: return uri;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: observationValues = (java.util.List<java.lang.Double>)value$; break;
    case 1: label = (java.lang.CharSequence)value$; break;
    case 2: tStart = (java.lang.Long)value$; break;
    case 3: tEnd = (java.lang.Long)value$; break;
    case 4: zObservations = (java.lang.Long)value$; break;
    case 5: increment = (java.lang.Integer)value$; break;
    case 6: uri = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'observationValues' field.
   * @return The value of the 'observationValues' field.
   */
  public java.util.List<java.lang.Double> getObservationValues() {
    return observationValues;
  }

  /**
   * Sets the value of the 'observationValues' field.
   * @param value the value to set.
   */
  public void setObservationValues(java.util.List<java.lang.Double> value) {
    this.observationValues = value;
  }

  /**
   * Gets the value of the 'label' field.
   * @return The value of the 'label' field.
   */
  public java.lang.CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(java.lang.CharSequence value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'tStart' field.
   * @return The value of the 'tStart' field.
   */
  public java.lang.Long getTStart() {
    return tStart;
  }

  /**
   * Sets the value of the 'tStart' field.
   * @param value the value to set.
   */
  public void setTStart(java.lang.Long value) {
    this.tStart = value;
  }

  /**
   * Gets the value of the 'tEnd' field.
   * @return The value of the 'tEnd' field.
   */
  public java.lang.Long getTEnd() {
    return tEnd;
  }

  /**
   * Sets the value of the 'tEnd' field.
   * @param value the value to set.
   */
  public void setTEnd(java.lang.Long value) {
    this.tEnd = value;
  }

  /**
   * Gets the value of the 'zObservations' field.
   * @return The value of the 'zObservations' field.
   */
  public java.lang.Long getZObservations() {
    return zObservations;
  }

  /**
   * Sets the value of the 'zObservations' field.
   * @param value the value to set.
   */
  public void setZObservations(java.lang.Long value) {
    this.zObservations = value;
  }

  /**
   * Gets the value of the 'increment' field.
   * @return Time increment in ms.
   */
  public java.lang.Integer getIncrement() {
    return increment;
  }

  /**
   * Sets the value of the 'increment' field.
   * Time increment in ms.
   * @param value the value to set.
   */
  public void setIncrement(java.lang.Integer value) {
    this.increment = value;
  }

  /**
   * Gets the value of the 'uri' field.
   * @return The value of the 'uri' field.
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /**
   * Creates a new EpisodesNEW RecordBuilder.
   * @return A new EpisodesNEW RecordBuilder
   */
  public static org.opentsx.data.model.EpisodesNEW.Builder newBuilder() {
    return new org.opentsx.data.model.EpisodesNEW.Builder();
  }

  /**
   * Creates a new EpisodesNEW RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EpisodesNEW RecordBuilder
   */
  public static org.opentsx.data.model.EpisodesNEW.Builder newBuilder(org.opentsx.data.model.EpisodesNEW.Builder other) {
    return new org.opentsx.data.model.EpisodesNEW.Builder(other);
  }

  /**
   * Creates a new EpisodesNEW RecordBuilder by copying an existing EpisodesNEW instance.
   * @param other The existing instance to copy.
   * @return A new EpisodesNEW RecordBuilder
   */
  public static org.opentsx.data.model.EpisodesNEW.Builder newBuilder(org.opentsx.data.model.EpisodesNEW other) {
    return new org.opentsx.data.model.EpisodesNEW.Builder(other);
  }

  /**
   * RecordBuilder for EpisodesNEW instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EpisodesNEW>
    implements org.apache.avro.data.RecordBuilder<EpisodesNEW> {

    private java.util.List<java.lang.Double> observationValues;
    private java.lang.CharSequence label;
    private long tStart;
    private long tEnd;
    private long zObservations;
    /** Time increment in ms. */
    private int increment;
    private java.lang.CharSequence uri;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.opentsx.data.model.EpisodesNEW.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.observationValues)) {
        this.observationValues = data().deepCopy(fields()[0].schema(), other.observationValues);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tStart)) {
        this.tStart = data().deepCopy(fields()[2].schema(), other.tStart);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.tEnd)) {
        this.tEnd = data().deepCopy(fields()[3].schema(), other.tEnd);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.zObservations)) {
        this.zObservations = data().deepCopy(fields()[4].schema(), other.zObservations);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.increment)) {
        this.increment = data().deepCopy(fields()[5].schema(), other.increment);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.uri)) {
        this.uri = data().deepCopy(fields()[6].schema(), other.uri);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EpisodesNEW instance
     * @param other The existing instance to copy.
     */
    private Builder(org.opentsx.data.model.EpisodesNEW other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.observationValues)) {
        this.observationValues = data().deepCopy(fields()[0].schema(), other.observationValues);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tStart)) {
        this.tStart = data().deepCopy(fields()[2].schema(), other.tStart);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.tEnd)) {
        this.tEnd = data().deepCopy(fields()[3].schema(), other.tEnd);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.zObservations)) {
        this.zObservations = data().deepCopy(fields()[4].schema(), other.zObservations);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.increment)) {
        this.increment = data().deepCopy(fields()[5].schema(), other.increment);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.uri)) {
        this.uri = data().deepCopy(fields()[6].schema(), other.uri);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'observationValues' field.
      * @return The value.
      */
    public java.util.List<java.lang.Double> getObservationValues() {
      return observationValues;
    }

    /**
      * Sets the value of the 'observationValues' field.
      * @param value The value of 'observationValues'.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder setObservationValues(java.util.List<java.lang.Double> value) {
      validate(fields()[0], value);
      this.observationValues = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'observationValues' field has been set.
      * @return True if the 'observationValues' field has been set, false otherwise.
      */
    public boolean hasObservationValues() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'observationValues' field.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder clearObservationValues() {
      observationValues = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'label' field.
      * @return The value.
      */
    public java.lang.CharSequence getLabel() {
      return label;
    }

    /**
      * Sets the value of the 'label' field.
      * @param value The value of 'label'.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder setLabel(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.label = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'label' field has been set.
      * @return True if the 'label' field has been set, false otherwise.
      */
    public boolean hasLabel() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'label' field.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder clearLabel() {
      label = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tStart' field.
      * @return The value.
      */
    public java.lang.Long getTStart() {
      return tStart;
    }

    /**
      * Sets the value of the 'tStart' field.
      * @param value The value of 'tStart'.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder setTStart(long value) {
      validate(fields()[2], value);
      this.tStart = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tStart' field has been set.
      * @return True if the 'tStart' field has been set, false otherwise.
      */
    public boolean hasTStart() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tStart' field.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder clearTStart() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'tEnd' field.
      * @return The value.
      */
    public java.lang.Long getTEnd() {
      return tEnd;
    }

    /**
      * Sets the value of the 'tEnd' field.
      * @param value The value of 'tEnd'.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder setTEnd(long value) {
      validate(fields()[3], value);
      this.tEnd = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'tEnd' field has been set.
      * @return True if the 'tEnd' field has been set, false otherwise.
      */
    public boolean hasTEnd() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'tEnd' field.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder clearTEnd() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'zObservations' field.
      * @return The value.
      */
    public java.lang.Long getZObservations() {
      return zObservations;
    }

    /**
      * Sets the value of the 'zObservations' field.
      * @param value The value of 'zObservations'.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder setZObservations(long value) {
      validate(fields()[4], value);
      this.zObservations = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'zObservations' field has been set.
      * @return True if the 'zObservations' field has been set, false otherwise.
      */
    public boolean hasZObservations() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'zObservations' field.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder clearZObservations() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'increment' field.
      * Time increment in ms.
      * @return The value.
      */
    public java.lang.Integer getIncrement() {
      return increment;
    }

    /**
      * Sets the value of the 'increment' field.
      * Time increment in ms.
      * @param value The value of 'increment'.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder setIncrement(int value) {
      validate(fields()[5], value);
      this.increment = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'increment' field has been set.
      * Time increment in ms.
      * @return True if the 'increment' field has been set, false otherwise.
      */
    public boolean hasIncrement() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'increment' field.
      * Time increment in ms.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder clearIncrement() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'uri' field.
      * @return The value.
      */
    public java.lang.CharSequence getUri() {
      return uri;
    }

    /**
      * Sets the value of the 'uri' field.
      * @param value The value of 'uri'.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.uri = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'uri' field has been set.
      * @return True if the 'uri' field has been set, false otherwise.
      */
    public boolean hasUri() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'uri' field.
      * @return This builder.
      */
    public org.opentsx.data.model.EpisodesNEW.Builder clearUri() {
      uri = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EpisodesNEW build() {
      try {
        EpisodesNEW record = new EpisodesNEW();
        record.observationValues = fieldSetFlags()[0] ? this.observationValues : (java.util.List<java.lang.Double>) defaultValue(fields()[0]);
        record.label = fieldSetFlags()[1] ? this.label : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.tStart = fieldSetFlags()[2] ? this.tStart : (java.lang.Long) defaultValue(fields()[2]);
        record.tEnd = fieldSetFlags()[3] ? this.tEnd : (java.lang.Long) defaultValue(fields()[3]);
        record.zObservations = fieldSetFlags()[4] ? this.zObservations : (java.lang.Long) defaultValue(fields()[4]);
        record.increment = fieldSetFlags()[5] ? this.increment : (java.lang.Integer) defaultValue(fields()[5]);
        record.uri = fieldSetFlags()[6] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EpisodesNEW>
    WRITER$ = (org.apache.avro.io.DatumWriter<EpisodesNEW>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EpisodesNEW>
    READER$ = (org.apache.avro.io.DatumReader<EpisodesNEW>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
