
package ws.cache3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HBaseCacheService", targetNamespace = "http://cache.ts.hadoop/", wsdlLocation = "http://localhost:8080/TSCache/HBaseCacheService?wsdl")
public class HBaseCacheService
    extends Service
{

    private final static URL HBASECACHESERVICE_WSDL_LOCATION;
    private final static WebServiceException HBASECACHESERVICE_EXCEPTION;
    private final static QName HBASECACHESERVICE_QNAME = new QName("http://cache.ts.hadoop/", "HBaseCacheService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TSCache/HBaseCacheService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HBASECACHESERVICE_WSDL_LOCATION = url;
        HBASECACHESERVICE_EXCEPTION = e;
    }

    public HBaseCacheService() {
        super(__getWsdlLocation(), HBASECACHESERVICE_QNAME);
    }

    public HBaseCacheService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HBASECACHESERVICE_QNAME, features);
    }

    public HBaseCacheService(URL wsdlLocation) {
        super(wsdlLocation, HBASECACHESERVICE_QNAME);
    }

    public HBaseCacheService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HBASECACHESERVICE_QNAME, features);
    }

    public HBaseCacheService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HBaseCacheService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TSCacheV3
     */
    @WebEndpoint(name = "TSCache.v3Port")
    public TSCacheV3 getTSCacheV3Port() {
        return super.getPort(new QName("http://cache.ts.hadoop/", "TSCache.v3Port"), TSCacheV3.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TSCacheV3
     */
    @WebEndpoint(name = "TSCache.v3Port")
    public TSCacheV3 getTSCacheV3Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://cache.ts.hadoop/", "TSCache.v3Port"), TSCacheV3.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HBASECACHESERVICE_EXCEPTION!= null) {
            throw HBASECACHESERVICE_EXCEPTION;
        }
        return HBASECACHESERVICE_WSDL_LOCATION;
    }

}
