package org.opentsx.model;

import com.fasterxml.jackson.core.json.JsonReadFeature;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.json.JsonMapper;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.Map;

/** Loads the shared Java/Python test vectors (generated by testvectors/generate.py). */
final class TestVectors {

    private static final JsonMapper JSON = JsonMapper.builder()
            .enable(JsonReadFeature.ALLOW_NON_NUMERIC_NUMBERS)
            .build();

    private TestVectors() {
    }

    static JsonNode load(String name) {
        try (InputStream in = TestVectors.class.getResourceAsStream("/testvectors/" + name)) {
            if (in == null) {
                throw new IllegalStateException("missing test vector file " + name);
            }
            return JSON.readTree(in);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    static Map<String, String> map(JsonNode node) {
        Map<String, String> out = new LinkedHashMap<>();
        node.fields().forEachRemaining(e -> out.put(e.getKey(), e.getValue().asText()));
        return out;
    }

    static long[] longs(JsonNode node) {
        long[] out = new long[node.size()];
        for (int i = 0; i < out.length; i++) {
            out[i] = node.get(i).asLong();
        }
        return out;
    }

    static double[] doubles(JsonNode node) {
        double[] out = new double[node.size()];
        for (int i = 0; i < out.length; i++) {
            out[i] = node.get(i).asDouble();
        }
        return out;
    }

    static String hex(byte[] bytes) {
        return HexFormat.of().formatHex(bytes);
    }

    static byte[] bytes(String hex) {
        return HexFormat.of().parseHex(hex);
    }
}
