/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.opentsx.net.clusterscan;

import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 * Cluster-Checker: A Swing-based GUI application for scanning and monitoring cluster nodes.
 *
 * <p>This utility provides a graphical interface for cluster administrators to:
 * <ul>
 *   <li>Scan IP address ranges using CIDR notation (e.g., 192.168.3.255/24)</li>
 *   <li>Identify reachable nodes within the cluster</li>
 *   <li>Display available computers and services in a tabbed interface</li>
 *   <li>Monitor cluster node availability in real-time</li>
 * </ul>
 *
 * <h2>Usage Example:</h2>
 * <pre>{@code
 * // Launch the GUI
 * java -cp application-tools.jar org.opentsx.net.clusterscan.ClusterCheck
 *
 * // In the GUI:
 * // 1. Enter IP range: 192.168.1.0/24
 * // 2. Click "scan ip-range"
 * // 3. View available nodes in the list
 * }</pre>
 *
 * <h2>Features:</h2>
 * <ul>
 *   <li><b>IP Range Scanning:</b> Supports CIDR notation for flexible network scanning</li>
 *   <li><b>Reachability Detection:</b> Uses ICMP ping to detect live nodes</li>
 *   <li><b>Tabbed Interface:</b> Separate views for computers and services</li>
 *   <li><b>Real-time Updates:</b> Dynamic list updates as nodes are discovered</li>
 * </ul>
 *
 * <h2>Technical Details:</h2>
 * This class uses {@link ScanIPS} for the actual IP scanning logic and provides
 * a Swing-based UI for user interaction. The GUI is generated using NetBeans
 * Form Designer (generated code sections should not be manually modified).
 *
 * @author kamir
 * @version 1.0.0
 * @see ScanIPS
 * @see InetAddress
 * @since OpenTSx 3.0.0
 */
public class ClusterCheck extends javax.swing.JFrame {

    /**
     * Creates new form ClusterCheck
     */
    public ClusterCheck() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cluster-Checker v1.0.0");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Computers", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Services", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 85));

        jButton1.setText("scan ip-range");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("192.168.3.255/24");

        jButton2.setText("scan services");

        jLabel1.setText("IP-Range : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 
        scanRange(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClusterCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClusterCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClusterCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClusterCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClusterCheck().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    /**
     * Resets the view to its initial state.
     *
     * <p>Currently not implemented. Reserved for future use to clear
     * scan results and reset UI components.
     */
    private void resetView() {
        // Reserved for future implementation
    }

    /**
     * Scans the IP range specified in the text field and updates the display with reachable nodes.
     *
     * <p>This method:
     * <ol>
     *   <li>Reads the CIDR notation from the input text field (e.g., "192.168.3.255/24")</li>
     *   <li>Uses {@link ScanIPS} to scan all addresses in the range</li>
     *   <li>Tests reachability of each address using ICMP ping</li>
     *   <li>Updates the GUI list with all reachable nodes</li>
     * </ol>
     *
     * <p><b>Example Input:</b> {@code 192.168.1.0/24} scans addresses from 192.168.1.0 to 192.168.1.255
     *
     * <p><b>Performance:</b> Scanning large ranges may take time. Each node is tested with
     * a 100ms timeout. For a /24 network (256 addresses), expect ~25 seconds maximum scan time.
     *
     * @throws UnknownHostException if the IP range format is invalid
     * @throws IOException if network communication fails during scanning
     * @see ScanIPS#scanRange(String)
     */
    private void scanRange() {
        ScanIPS scanner = new ScanIPS();
        try {
            Vector<InetAddress> available = scanner.scanRange(this.jTextField1.getText());

            DefaultListModel dlm = new DefaultListModel();
            for (InetAddress a : available) {
                dlm.addElement(a);
            }
            this.jList1.setModel(dlm);
            this.repaint();
        }
        catch (UnknownHostException ex) {
            Logger.getLogger(ClusterCheck.class.getName()).log(Level.SEVERE,
                "Invalid IP range format: " + this.jTextField1.getText(), ex);
        } catch (IOException ex) {
            Logger.getLogger(ClusterCheck.class.getName()).log(Level.SEVERE,
                "Network error during IP range scan", ex);
        }
    }
}
