/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package chart.panels;

import data.series.Messreihe;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/**
 *
 * @author kamir
 */
public class MessreiheWindow3Frame extends javax.swing.JDialog {

    static int maxFrames = 10;
    static int anzFrames = 0;
    
    boolean canBeUsed = true;
    
    /**
     * Creates new form MessreiheWindow3Frame
     */
    public MessreiheWindow3Frame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
        Messreihe mr1 = new Messreihe();
        Messreihe mr2 = new Messreihe();
        Messreihe mr3 = new Messreihe();

    public MessreiheWindow3Frame() {
        super( new JFrame(), false );
        if ( anzFrames < maxFrames ) {
            anzFrames++;
        }
        else {
            canBeUsed = false;
        }
    }
    
    public void show( Vector<Double>dataRawTIMES , Vector<Double>dataRawFILTERED, Vector<Double>dataRawNOT_FILTERED ) { 

        if ( canBeUsed ) {
             
            initComponents();
            
            for( double v: dataRawTIMES ) {
              mr1.addValue( v );
            };
    
            for( double v: dataRawFILTERED ) {
                mr2.addValue( v );
            };
            
            for( double v: dataRawNOT_FILTERED ) {
                mr3.addValue( v );
            }
            
            
            setVisible(true);
            jTextArea1.setText( mr1.toString() ); 
            jTextArea2.setText( mr2.toString() ); 
            jTextArea3.setText( mr3.toString() ); 
            
             
                
        }
        
        
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("OK");
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void open(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessreiheWindow3Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessreiheWindow3Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessreiheWindow3Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessreiheWindow3Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MessreiheWindow3Frame dialog = new MessreiheWindow3Frame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                dialog.jTextArea1.setText( mr1.toString() ); 
                dialog.jTextArea2.setText( mr2.toString() ); 
                dialog.jTextArea3.setText( mr3.toString() ); 
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
