/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cloudera.tsa.data;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WebResource extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WebResource\",\"namespace\":\"com.cloudera.tsa.data\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"kOut\",\"type\":\"long\"},{\"name\":\"context\",\"type\":\"string\"},{\"name\":\"depth\",\"type\":\"int\"},{\"name\":\"run\",\"type\":\"string\"},{\"name\":\"plainContent\",\"type\":\"string\"},{\"name\":\"parsedContent\",\"type\":\"string\"},{\"name\":\"lText\",\"type\":\"long\"},{\"name\":\"lHTML\",\"type\":\"long\"},{\"name\":\"lang\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence uri;
  @Deprecated public long kOut;
  @Deprecated public java.lang.CharSequence context;
  @Deprecated public int depth;
  @Deprecated public java.lang.CharSequence run;
  @Deprecated public java.lang.CharSequence plainContent;
  @Deprecated public java.lang.CharSequence parsedContent;
  @Deprecated public long lText;
  @Deprecated public long lHTML;
  @Deprecated public java.lang.CharSequence lang;

  /**
   * Default constructor.
   */
  public WebResource() {}

  /**
   * All-args constructor.
   */
  public WebResource(java.lang.CharSequence uri, java.lang.Long kOut, java.lang.CharSequence context, java.lang.Integer depth, java.lang.CharSequence run, java.lang.CharSequence plainContent, java.lang.CharSequence parsedContent, java.lang.Long lText, java.lang.Long lHTML, java.lang.CharSequence lang) {
    this.uri = uri;
    this.kOut = kOut;
    this.context = context;
    this.depth = depth;
    this.run = run;
    this.plainContent = plainContent;
    this.parsedContent = parsedContent;
    this.lText = lText;
    this.lHTML = lHTML;
    this.lang = lang;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uri;
    case 1: return kOut;
    case 2: return context;
    case 3: return depth;
    case 4: return run;
    case 5: return plainContent;
    case 6: return parsedContent;
    case 7: return lText;
    case 8: return lHTML;
    case 9: return lang;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uri = (java.lang.CharSequence)value$; break;
    case 1: kOut = (java.lang.Long)value$; break;
    case 2: context = (java.lang.CharSequence)value$; break;
    case 3: depth = (java.lang.Integer)value$; break;
    case 4: run = (java.lang.CharSequence)value$; break;
    case 5: plainContent = (java.lang.CharSequence)value$; break;
    case 6: parsedContent = (java.lang.CharSequence)value$; break;
    case 7: lText = (java.lang.Long)value$; break;
    case 8: lHTML = (java.lang.Long)value$; break;
    case 9: lang = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uri' field.
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'kOut' field.
   */
  public java.lang.Long getKOut() {
    return kOut;
  }

  /**
   * Sets the value of the 'kOut' field.
   * @param value the value to set.
   */
  public void setKOut(java.lang.Long value) {
    this.kOut = value;
  }

  /**
   * Gets the value of the 'context' field.
   */
  public java.lang.CharSequence getContext() {
    return context;
  }

  /**
   * Sets the value of the 'context' field.
   * @param value the value to set.
   */
  public void setContext(java.lang.CharSequence value) {
    this.context = value;
  }

  /**
   * Gets the value of the 'depth' field.
   */
  public java.lang.Integer getDepth() {
    return depth;
  }

  /**
   * Sets the value of the 'depth' field.
   * @param value the value to set.
   */
  public void setDepth(java.lang.Integer value) {
    this.depth = value;
  }

  /**
   * Gets the value of the 'run' field.
   */
  public java.lang.CharSequence getRun() {
    return run;
  }

  /**
   * Sets the value of the 'run' field.
   * @param value the value to set.
   */
  public void setRun(java.lang.CharSequence value) {
    this.run = value;
  }

  /**
   * Gets the value of the 'plainContent' field.
   */
  public java.lang.CharSequence getPlainContent() {
    return plainContent;
  }

  /**
   * Sets the value of the 'plainContent' field.
   * @param value the value to set.
   */
  public void setPlainContent(java.lang.CharSequence value) {
    this.plainContent = value;
  }

  /**
   * Gets the value of the 'parsedContent' field.
   */
  public java.lang.CharSequence getParsedContent() {
    return parsedContent;
  }

  /**
   * Sets the value of the 'parsedContent' field.
   * @param value the value to set.
   */
  public void setParsedContent(java.lang.CharSequence value) {
    this.parsedContent = value;
  }

  /**
   * Gets the value of the 'lText' field.
   */
  public java.lang.Long getLText() {
    return lText;
  }

  /**
   * Sets the value of the 'lText' field.
   * @param value the value to set.
   */
  public void setLText(java.lang.Long value) {
    this.lText = value;
  }

  /**
   * Gets the value of the 'lHTML' field.
   */
  public java.lang.Long getLHTML() {
    return lHTML;
  }

  /**
   * Sets the value of the 'lHTML' field.
   * @param value the value to set.
   */
  public void setLHTML(java.lang.Long value) {
    this.lHTML = value;
  }

  /**
   * Gets the value of the 'lang' field.
   */
  public java.lang.CharSequence getLang() {
    return lang;
  }

  /**
   * Sets the value of the 'lang' field.
   * @param value the value to set.
   */
  public void setLang(java.lang.CharSequence value) {
    this.lang = value;
  }

  /** Creates a new WebResource RecordBuilder */
  public static com.cloudera.tsa.data.WebResource.Builder newBuilder() {
    return new com.cloudera.tsa.data.WebResource.Builder();
  }
  
  /** Creates a new WebResource RecordBuilder by copying an existing Builder */
  public static com.cloudera.tsa.data.WebResource.Builder newBuilder(com.cloudera.tsa.data.WebResource.Builder other) {
    return new com.cloudera.tsa.data.WebResource.Builder(other);
  }
  
  /** Creates a new WebResource RecordBuilder by copying an existing WebResource instance */
  public static com.cloudera.tsa.data.WebResource.Builder newBuilder(com.cloudera.tsa.data.WebResource other) {
    return new com.cloudera.tsa.data.WebResource.Builder(other);
  }
  
  /**
   * RecordBuilder for WebResource instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WebResource>
    implements org.apache.avro.data.RecordBuilder<WebResource> {

    private java.lang.CharSequence uri;
    private long kOut;
    private java.lang.CharSequence context;
    private int depth;
    private java.lang.CharSequence run;
    private java.lang.CharSequence plainContent;
    private java.lang.CharSequence parsedContent;
    private long lText;
    private long lHTML;
    private java.lang.CharSequence lang;

    /** Creates a new Builder */
    private Builder() {
      super(com.cloudera.tsa.data.WebResource.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cloudera.tsa.data.WebResource.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing WebResource instance */
    private Builder(com.cloudera.tsa.data.WebResource other) {
            super(com.cloudera.tsa.data.WebResource.SCHEMA$);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.kOut)) {
        this.kOut = data().deepCopy(fields()[1].schema(), other.kOut);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.context)) {
        this.context = data().deepCopy(fields()[2].schema(), other.context);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.depth)) {
        this.depth = data().deepCopy(fields()[3].schema(), other.depth);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.run)) {
        this.run = data().deepCopy(fields()[4].schema(), other.run);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.plainContent)) {
        this.plainContent = data().deepCopy(fields()[5].schema(), other.plainContent);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.parsedContent)) {
        this.parsedContent = data().deepCopy(fields()[6].schema(), other.parsedContent);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lText)) {
        this.lText = data().deepCopy(fields()[7].schema(), other.lText);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.lHTML)) {
        this.lHTML = data().deepCopy(fields()[8].schema(), other.lHTML);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.lang)) {
        this.lang = data().deepCopy(fields()[9].schema(), other.lang);
        fieldSetFlags()[9] = true;
      }
    }

    /** Gets the value of the 'uri' field */
    public java.lang.CharSequence getUri() {
      return uri;
    }
    
    /** Sets the value of the 'uri' field */
    public com.cloudera.tsa.data.WebResource.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.uri = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'uri' field has been set */
    public boolean hasUri() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'uri' field */
    public com.cloudera.tsa.data.WebResource.Builder clearUri() {
      uri = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'kOut' field */
    public java.lang.Long getKOut() {
      return kOut;
    }
    
    /** Sets the value of the 'kOut' field */
    public com.cloudera.tsa.data.WebResource.Builder setKOut(long value) {
      validate(fields()[1], value);
      this.kOut = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'kOut' field has been set */
    public boolean hasKOut() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'kOut' field */
    public com.cloudera.tsa.data.WebResource.Builder clearKOut() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'context' field */
    public java.lang.CharSequence getContext() {
      return context;
    }
    
    /** Sets the value of the 'context' field */
    public com.cloudera.tsa.data.WebResource.Builder setContext(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.context = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'context' field has been set */
    public boolean hasContext() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'context' field */
    public com.cloudera.tsa.data.WebResource.Builder clearContext() {
      context = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'depth' field */
    public java.lang.Integer getDepth() {
      return depth;
    }
    
    /** Sets the value of the 'depth' field */
    public com.cloudera.tsa.data.WebResource.Builder setDepth(int value) {
      validate(fields()[3], value);
      this.depth = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'depth' field has been set */
    public boolean hasDepth() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'depth' field */
    public com.cloudera.tsa.data.WebResource.Builder clearDepth() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'run' field */
    public java.lang.CharSequence getRun() {
      return run;
    }
    
    /** Sets the value of the 'run' field */
    public com.cloudera.tsa.data.WebResource.Builder setRun(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.run = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'run' field has been set */
    public boolean hasRun() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'run' field */
    public com.cloudera.tsa.data.WebResource.Builder clearRun() {
      run = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'plainContent' field */
    public java.lang.CharSequence getPlainContent() {
      return plainContent;
    }
    
    /** Sets the value of the 'plainContent' field */
    public com.cloudera.tsa.data.WebResource.Builder setPlainContent(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.plainContent = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'plainContent' field has been set */
    public boolean hasPlainContent() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'plainContent' field */
    public com.cloudera.tsa.data.WebResource.Builder clearPlainContent() {
      plainContent = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'parsedContent' field */
    public java.lang.CharSequence getParsedContent() {
      return parsedContent;
    }
    
    /** Sets the value of the 'parsedContent' field */
    public com.cloudera.tsa.data.WebResource.Builder setParsedContent(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.parsedContent = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'parsedContent' field has been set */
    public boolean hasParsedContent() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'parsedContent' field */
    public com.cloudera.tsa.data.WebResource.Builder clearParsedContent() {
      parsedContent = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'lText' field */
    public java.lang.Long getLText() {
      return lText;
    }
    
    /** Sets the value of the 'lText' field */
    public com.cloudera.tsa.data.WebResource.Builder setLText(long value) {
      validate(fields()[7], value);
      this.lText = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'lText' field has been set */
    public boolean hasLText() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'lText' field */
    public com.cloudera.tsa.data.WebResource.Builder clearLText() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'lHTML' field */
    public java.lang.Long getLHTML() {
      return lHTML;
    }
    
    /** Sets the value of the 'lHTML' field */
    public com.cloudera.tsa.data.WebResource.Builder setLHTML(long value) {
      validate(fields()[8], value);
      this.lHTML = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'lHTML' field has been set */
    public boolean hasLHTML() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'lHTML' field */
    public com.cloudera.tsa.data.WebResource.Builder clearLHTML() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'lang' field */
    public java.lang.CharSequence getLang() {
      return lang;
    }
    
    /** Sets the value of the 'lang' field */
    public com.cloudera.tsa.data.WebResource.Builder setLang(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.lang = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'lang' field has been set */
    public boolean hasLang() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'lang' field */
    public com.cloudera.tsa.data.WebResource.Builder clearLang() {
      lang = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    public WebResource build() {
      try {
        WebResource record = new WebResource();
        record.uri = fieldSetFlags()[0] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.kOut = fieldSetFlags()[1] ? this.kOut : (java.lang.Long) defaultValue(fields()[1]);
        record.context = fieldSetFlags()[2] ? this.context : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.depth = fieldSetFlags()[3] ? this.depth : (java.lang.Integer) defaultValue(fields()[3]);
        record.run = fieldSetFlags()[4] ? this.run : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.plainContent = fieldSetFlags()[5] ? this.plainContent : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.parsedContent = fieldSetFlags()[6] ? this.parsedContent : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.lText = fieldSetFlags()[7] ? this.lText : (java.lang.Long) defaultValue(fields()[7]);
        record.lHTML = fieldSetFlags()[8] ? this.lHTML : (java.lang.Long) defaultValue(fields()[8]);
        record.lang = fieldSetFlags()[9] ? this.lang : (java.lang.CharSequence) defaultValue(fields()[9]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
